runtime: python27
api_version: 1
threadsafe: true
service: default

handlers:
- url: /static
  static_dir: static/
- url: .*
  script: retail_cannabis_business_app.wsgi.application


# Only pure Python libraries can be vendored
# Python libraries that use C extensions can
# only be included if they are part of the App Engine SDK
# Using Third Party Libraries: https://cloud.google.com/appengine/docs/python/tools/using-libraries-python-27
#libraries:
libraries:
- name: pycrypto
  version: 2.6
- name: ssl
  version: 2.7.11
- name: MySQLdb
  version: 1.2.5
- name: PIL
  version: 1.1.7

# Google App Engine limits application deployments to 10,000 uploaded files per
# version. The skip_files section allows us to skip virtual environment files
# to meet this requirement.
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?setuptools/script \(dev\).tmpl$
- ^(.*/)?.*\.sh$
- ^(.*/)?.*\.sql$
- ^(.*/)?venv/.*
- ^(.*/)?.*data\.json$