# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 07:06
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_to_video', models.URLField(blank=True, null=True)),
                ('date', models.DateField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(
                    choices=[('CNT_SUP', 'County Board of Supervisors'), ('CNT_SHR', 'County Sheriff'),
                             ('CNT_HPL', 'County Head Planner'), ('CNT_MGR', 'County Manager'),
                             ('CTY_CNL', 'City Council')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=5)),
                ('address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('civil_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married')], max_length=5)),
                ('job_title', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=50)),
                ('political_stance', models.CharField(choices=[('R', 'Republican'), ('D', 'Democrat')], max_length=5)),
                ('supports_cannabis_usage', models.BooleanField(default=False)),
                ('annual_financial_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('annual_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('organizations', models.TextField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_area', models.DecimalField(decimal_places=4, max_digits=12)),
                ('population', models.PositiveIntegerField()),
                ('financial_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('financial_income_per_capita', models.DecimalField(decimal_places=2, max_digits=12)),
                ('business_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cannabis_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dominant_political_stance',
                 models.CharField(choices=[('R', 'Republican'), ('D', 'Democrat')], max_length=5)),
                ('vote_percent_democrat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vote_percent_republican', models.DecimalField(decimal_places=2, max_digits=5)),
                ('approved_cannabis', models.BooleanField(default=False)),
                ('prop_64_vote', models.BooleanField(default=False)),
                ('vote_percent_prop_64', models.DecimalField(decimal_places=2, max_digits=5)),
                ('medical_use', models.BooleanField(default=False)),
                ('cultivation_license', models.BooleanField(default=False)),
                ('cultivation_allowed_areas', models.TextField()),
                ('manufacturing_license', models.BooleanField(default=False)),
                ('manufacturing_allowed_areas', models.TextField()),
                ('retail_license', models.BooleanField(default=False)),
                ('retail_allowed_areas', models.TextField()),
                ('distribution_license', models.BooleanField(default=False)),
                ('microbusiness_license', models.BooleanField(default=False)),
                ('laboratory_license', models.BooleanField(default=False)),
                ('cannabis_consultant_start_date', models.DateField(blank=True, null=True)),
                ('other_localities_consulted', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_std', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telephone_number', models.CharField(max_length=20)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConsultantCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telephone_number', models.CharField(max_length=20)),
                ('fax_number', models.CharField(max_length=20)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LocalGovUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=50)),
                ('city',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ordinances.City')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_std', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_std', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordinances.Region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='localgovunit',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordinances.SubRegion'),
        ),
        migrations.AddField(
            model_name='localgovunit',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordinances.Region'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='ordinances.ConsultantCompany'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordinances.Region'),
        ),
        migrations.AddField(
            model_name='city',
            name='subregion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordinances.SubRegion'),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='cannabis_consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='ordinances.ConsultantCompany'),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='local_gov_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='ordinances.LocalGovUnit'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='business_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='ordinances.BusinessInfo'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='local_gov_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='ordinances.LocalGovUnit'),
        ),
        migrations.AlterUniqueTogether(
            name='localgovunit',
            unique_together=set([('county', 'city')]),
        ),
    ]
