# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 09:04
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ordinances', '0002_auto_20171127_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessinfo',
            name='cannabis_consultant',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='business_info',
        ),
        migrations.AddField(
            model_name='agenda',
            name='approved_cannabis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agenda',
            name='business_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda',
            name='cannabis_consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='ordinances.ConsultantCompany'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='cannabis_consultant_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='cannabis_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda',
            name='cultivation_allowed_areas',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda',
            name='cultivation_license',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agenda',
            name='distribution_license',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agenda',
            name='dominant_political_stance',
            field=models.CharField(choices=[('R', 'Republican'), ('D', 'Democrat')], default='R', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda',
            name='financial_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda',
            name='financial_income_per_capita',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda',
            name='laboratory_license',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agenda',
            name='land_area',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda',
            name='manufacturing_allowed_areas',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda',
            name='manufacturing_license',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agenda',
            name='medical_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agenda',
            name='microbusiness_license',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agenda',
            name='other_localities_consulted',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda',
            name='population',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda',
            name='prop_64_vote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agenda',
            name='retail_allowed_areas',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda',
            name='retail_license',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agenda',
            name='vote_percent_democrat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda',
            name='vote_percent_prop_64',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda',
            name='vote_percent_republican',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BusinessInfo',
        ),
    ]
