# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 03:02
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ordinances', '0003_auto_20171127_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='subregion',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='agenda',
            name='local_gov_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendas',
                                    to='ordinances.LocalGovUnit'),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='local_gov_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='board_members', to='ordinances.LocalGovUnit'),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities',
                                    to='ordinances.Region'),
        ),
        migrations.AlterField(
            model_name='city',
            name='subregion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities',
                                    to='ordinances.SubRegion'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultants',
                                    to='ordinances.ConsultantCompany'),
        ),
        migrations.AlterField(
            model_name='subregion',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subregions',
                                    to='ordinances.Region'),
        ),
    ]
