# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 08:37
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ordinances', '0004_auto_20171204_0302'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='localgovunit',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='localgovunit',
            name='city',
        ),
        migrations.RemoveField(
            model_name='localgovunit',
            name='county',
        ),
        migrations.RemoveField(
            model_name='localgovunit',
            name='state',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='local_gov_unit',
        ),
        migrations.RemoveField(
            model_name='boardmember',
            name='local_gov_unit',
        ),
        migrations.AddField(
            model_name='agenda',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendas',
                                    to='ordinances.City'),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='board_members', to='ordinances.City'),
        ),
        migrations.DeleteModel(
            name='LocalGovUnit',
        ),
    ]
