# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ordinances', '0005_auto_20171204_0837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='agenda',
            name='other_localities_consulted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
