# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordinances', '0007_auto_20171206_0618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='cannabis_consultant',
            new_name='cannabis_consultant_company',
        ),
        migrations.AddField(
            model_name='agenda',
            name='cannabis_consultant_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordinances.Consultant'),
        ),
    ]
