# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordinances', '0009_auto_20171212_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmember',
            name='city',
        ),
        migrations.AddField(
            model_name='boardmember',
            name='agenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_members', to='ordinances.Agenda'),
        ),
    ]
