# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordinances', '0010_auto_20171212_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.CharField(choices=[('CNT_SUP', 'County Board of Supervisors'), ('CNT_SHR', 'County Sheriff'), ('CNT_HPL', 'County Head Planner'), ('CNT_MGR', 'County Manager'), ('CTY_CNL', 'City Council')], max_length=10)),
                ('job_title', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=50)),
                ('political_stance', models.CharField(choices=[('R', 'Republican'), ('D', 'Democrat')], max_length=5)),
                ('supports_cannabis_usage', models.BooleanField(default=False)),
                ('notes', models.TextField()),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='ordinances.Agenda')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='ordinances.Agenda')),
            ],
            options={
                'verbose_name': 'Board Member',
            },
        ),
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='politicians', to='ordinances.City')),
                ('subregion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politicians', to='ordinances.SubRegion')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='boardmember',
            name='agenda',
        ),
        migrations.DeleteModel(
            name='BoardMember',
        ),
    ]
