# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordinances', '0011_auto_20171213_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='politician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='ordinances.Politician'),
        ),
    ]
