# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordinances', '0013_auto_20171213_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='subregion',
            field=models.ForeignKey(default=5322745, on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='ordinances.SubRegion'),
            preserve_default=False,
        ),
    ]
