# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinances', '0014_agenda_subregion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politician',
            name='image_url',
        ),
        migrations.AddField(
            model_name='politician',
            name='image_path',
            field=models.CharField(blank=True, default='assets/blank_male_avatar.jpg', max_length=200, null=True),
        ),
    ]
