# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordinances', '0015_auto_20171214_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='age',
        ),
    ]
