# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinances', '0016_remove_consultant_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='image_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
